<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Honda N BOX G SENSING 2023',
                'description' => 'Excellent condition Honda N BOX with G SENSING package. Low mileage, well maintained. Perfect for city driving.',
                'brand' => 'HONDA',
                'category' => 'Vehicles',
                'model' => 'N BOX',
                'price' => 12500.00,
                'condition' => 'Used',
                'part_number' => 'VH-NBOX-2023',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82406',
                'chassis_number' => 'JF3-528****',
                'model_code' => '68A-JF3',
                'year_month' => '2023/4',
                'grade' => 'G SENSING',
                'body_style' => 'HATCHBACK',
                'mileage' => 8000,
                'transmission' => 'AUTOMATIC',
                'engine_cc' => 660,
                'fuel_type' => 'GASOLINE',
                'color' => 'BLACK',
                'doors' => 4,
                'seats' => 4,
                'dimension' => '339 X 147 X 179',
                'additional_features' => ['Power Window', 'Sun Roof', '4 Wheel Drive'],
            ],
            [
                'name' => 'Toyota Prius Hybrid 2022',
                'description' => 'Toyota Prius Hybrid in excellent condition. Fuel efficient, perfect for eco-conscious drivers.',
                'brand' => 'TOYOTA',
                'category' => 'Vehicles',
                'model' => 'Prius',
                'price' => 18500.00,
                'condition' => 'Used',
                'part_number' => 'VH-PRIUS-2022',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82407',
                'chassis_number' => 'JTD-123****',
                'model_code' => 'ZVW30',
                'year_month' => '2022/6',
                'grade' => 'S',
                'body_style' => 'SEDAN',
                'mileage' => 15000,
                'transmission' => 'CVT',
                'engine_cc' => 1800,
                'fuel_type' => 'HYBRID',
                'color' => 'WHITE',
                'doors' => 4,
                'seats' => 5,
                'dimension' => '454 X 176 X 149',
                'additional_features' => ['Power Window', 'Navigation System', 'Backup Camera', 'Keyless Entry'],
            ],
            [
                'name' => 'Nissan X-Trail 2021',
                'description' => 'Spacious SUV with excellent features. Perfect for families and long drives.',
                'brand' => 'NISSAN',
                'category' => 'Vehicles',
                'model' => 'X-Trail',
                'price' => 22000.00,
                'condition' => 'Used',
                'part_number' => 'VH-XTRAIL-2021',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82408',
                'chassis_number' => 'JN1-456****',
                'model_code' => 'T32',
                'year_month' => '2021/3',
                'grade' => 'ST',
                'body_style' => 'SUV',
                'mileage' => 25000,
                'transmission' => 'AUTOMATIC',
                'engine_cc' => 2000,
                'fuel_type' => 'GASOLINE',
                'color' => 'SILVER',
                'doors' => 5,
                'seats' => 7,
                'dimension' => '467 X 182 X 172',
                'additional_features' => ['Power Window', 'Sun Roof', '4 Wheel Drive', 'Leather Seats', 'Third Row Seating'],
            ],
            [
                'name' => 'Mazda CX-5 2020',
                'description' => 'Sporty and stylish SUV with premium features. Great handling and fuel economy.',
                'brand' => 'MAZDA',
                'category' => 'Vehicles',
                'model' => 'CX-5',
                'price' => 19500.00,
                'condition' => 'Used',
                'part_number' => 'VH-CX5-2020',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82409',
                'chassis_number' => 'JM3-789****',
                'model_code' => 'KE',
                'year_month' => '2020/8',
                'grade' => 'TOURING',
                'body_style' => 'SUV',
                'mileage' => 32000,
                'transmission' => 'AUTOMATIC',
                'engine_cc' => 2500,
                'fuel_type' => 'GASOLINE',
                'color' => 'RED',
                'doors' => 5,
                'seats' => 5,
                'dimension' => '455 X 184 X 168',
                'additional_features' => ['Power Window', 'Sun Roof', 'Bose Sound System', 'Heated Seats'],
            ],
            [
                'name' => 'Suzuki Swift 2023',
                'description' => 'Compact and efficient hatchback. Perfect for city driving with great fuel economy.',
                'brand' => 'SUZUKI',
                'category' => 'Vehicles',
                'model' => 'Swift',
                'price' => 9800.00,
                'condition' => 'Used',
                'part_number' => 'VH-SWIFT-2023',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82410',
                'chassis_number' => 'JS2-321****',
                'model_code' => 'ZC33S',
                'year_month' => '2023/2',
                'grade' => 'GLX',
                'body_style' => 'HATCHBACK',
                'mileage' => 5000,
                'transmission' => 'AUTOMATIC',
                'engine_cc' => 1200,
                'fuel_type' => 'GASOLINE',
                'color' => 'BLUE',
                'doors' => 5,
                'seats' => 5,
                'dimension' => '384 X 173 X 151',
                'additional_features' => ['Power Window', 'Touchscreen Display', 'Reverse Camera'],
            ],
            [
                'name' => 'Toyota Corolla 2021',
                'description' => 'Reliable and fuel-efficient sedan. Popular choice for daily commuting.',
                'brand' => 'TOYOTA',
                'category' => 'Vehicles',
                'model' => 'Corolla',
                'price' => 14500.00,
                'condition' => 'Used',
                'part_number' => 'VH-COROLLA-2021',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82411',
                'chassis_number' => 'ZRE-654****',
                'model_code' => 'ZRE182',
                'year_month' => '2021/5',
                'grade' => 'S',
                'body_style' => 'SEDAN',
                'mileage' => 28000,
                'transmission' => 'CVT',
                'engine_cc' => 1800,
                'fuel_type' => 'GASOLINE',
                'color' => 'GRAY',
                'doors' => 4,
                'seats' => 5,
                'dimension' => '463 X 178 X 143',
                'additional_features' => ['Power Window', 'Keyless Entry', 'Backup Camera'],
            ],
            [
                'name' => 'Honda Fit 2022',
                'description' => 'Spacious interior in a compact package. Great for urban environments.',
                'brand' => 'HONDA',
                'category' => 'Vehicles',
                'model' => 'Fit',
                'price' => 11200.00,
                'condition' => 'Used',
                'part_number' => 'VH-FIT-2022',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82412',
                'chassis_number' => 'GK5-987****',
                'model_code' => 'GK5',
                'year_month' => '2022/1',
                'grade' => 'RS',
                'body_style' => 'HATCHBACK',
                'mileage' => 12000,
                'transmission' => 'CVT',
                'engine_cc' => 1500,
                'fuel_type' => 'GASOLINE',
                'color' => 'YELLOW',
                'doors' => 5,
                'seats' => 5,
                'dimension' => '399 X 169 X 154',
                'additional_features' => ['Power Window', 'Magic Seats', 'Honda Sensing'],
            ],
            [
                'name' => 'Subaru Forester 2020',
                'description' => 'All-wheel drive SUV perfect for all weather conditions. Spacious and reliable.',
                'brand' => 'SUBARU',
                'category' => 'Vehicles',
                'model' => 'Forester',
                'price' => 21000.00,
                'condition' => 'Used',
                'part_number' => 'VH-FORESTER-2020',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82413',
                'chassis_number' => 'SJ5-147****',
                'model_code' => 'SJ5',
                'year_month' => '2020/9',
                'grade' => 'X',
                'body_style' => 'SUV',
                'mileage' => 35000,
                'transmission' => 'CVT',
                'engine_cc' => 2500,
                'fuel_type' => 'GASOLINE',
                'color' => 'GREEN',
                'doors' => 5,
                'seats' => 5,
                'dimension' => '462 X 181 X 173',
                'additional_features' => ['Power Window', '4 Wheel Drive', 'EyeSight System', 'Sun Roof'],
            ],
            [
                'name' => 'Mitsubishi Outlander 2021',
                'description' => '7-seater SUV with excellent space and features. Great for large families.',
                'brand' => 'MITSUBISHI',
                'category' => 'Vehicles',
                'model' => 'Outlander',
                'price' => 19800.00,
                'condition' => 'Used',
                'part_number' => 'VH-OUTLANDER-2021',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82414',
                'chassis_number' => 'JN1-258****',
                'model_code' => 'GG2W',
                'year_month' => '2021/7',
                'grade' => 'GLS',
                'body_style' => 'SUV',
                'mileage' => 22000,
                'transmission' => 'CVT',
                'engine_cc' => 2400,
                'fuel_type' => 'GASOLINE',
                'color' => 'WHITE',
                'doors' => 5,
                'seats' => 7,
                'dimension' => '470 X 182 X 171',
                'additional_features' => ['Power Window', 'Third Row Seating', '4 Wheel Drive', 'Panoramic Sunroof'],
            ],
            [
                'name' => 'Daihatsu Tanto 2023',
                'description' => 'Ultra-compact kei car perfect for narrow streets. Excellent fuel economy and maneuverability.',
                'brand' => 'DAIHATSU',
                'category' => 'Vehicles',
                'model' => 'Tanto',
                'price' => 8500.00,
                'condition' => 'Used',
                'part_number' => 'VH-TANTO-2023',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82415',
                'chassis_number' => 'LA100-369****',
                'model_code' => 'LA100',
                'year_month' => '2023/3',
                'grade' => 'X',
                'body_style' => 'HATCHBACK',
                'mileage' => 3000,
                'transmission' => 'CVT',
                'engine_cc' => 660,
                'fuel_type' => 'GASOLINE',
                'color' => 'PINK',
                'doors' => 4,
                'seats' => 4,
                'dimension' => '339 X 147 X 175',
                'additional_features' => ['Power Window', 'Keyless Entry', 'Reverse Camera'],
            ],
            [
                'name' => 'Toyota RAV4 2022',
                'description' => 'Popular compact SUV with excellent reliability and resale value. Perfect for adventure seekers.',
                'brand' => 'TOYOTA',
                'category' => 'Vehicles',
                'model' => 'RAV4',
                'price' => 22800.00,
                'condition' => 'Used',
                'part_number' => 'VH-RAV4-2022',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82416',
                'chassis_number' => 'JTMB-741****',
                'model_code' => 'XA50',
                'year_month' => '2022/4',
                'grade' => 'G',
                'body_style' => 'SUV',
                'mileage' => 18000,
                'transmission' => 'AUTOMATIC',
                'engine_cc' => 2500,
                'fuel_type' => 'GASOLINE',
                'color' => 'BLACK',
                'doors' => 5,
                'seats' => 5,
                'dimension' => '460 X 185 X 169',
                'additional_features' => ['Power Window', '4 Wheel Drive', 'Sun Roof', 'Toyota Safety Sense'],
            ],
            [
                'name' => 'Honda CR-V 2021',
                'description' => 'Comfortable and spacious SUV with Honda reliability. Great family vehicle with advanced safety features.',
                'brand' => 'HONDA',
                'category' => 'Vehicles',
                'model' => 'CR-V',
                'price' => 21500.00,
                'condition' => 'Used',
                'part_number' => 'VH-CRV-2021',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82417',
                'chassis_number' => 'JHM-852****',
                'model_code' => 'RW5',
                'year_month' => '2021/6',
                'grade' => 'EX',
                'body_style' => 'SUV',
                'mileage' => 24000,
                'transmission' => 'CVT',
                'engine_cc' => 2000,
                'fuel_type' => 'GASOLINE',
                'color' => 'SILVER',
                'doors' => 5,
                'seats' => 5,
                'dimension' => '459 X 186 X 168',
                'additional_features' => ['Power Window', 'Honda Sensing', 'Sun Roof', 'Leather Seats'],
            ],
            [
                'name' => 'Nissan Leaf 2023',
                'description' => 'Fully electric vehicle with zero emissions. Perfect for eco-conscious drivers and city commuting.',
                'brand' => 'NISSAN',
                'category' => 'Vehicles',
                'model' => 'Leaf',
                'price' => 16800.00,
                'condition' => 'Used',
                'part_number' => 'VH-LEAF-2023',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82418',
                'chassis_number' => 'JN1-963****',
                'model_code' => 'ZE1',
                'year_month' => '2023/1',
                'grade' => 'E',
                'body_style' => 'HATCHBACK',
                'mileage' => 6000,
                'transmission' => 'AUTOMATIC',
                'engine_cc' => 0,
                'fuel_type' => 'ELECTRIC',
                'color' => 'BLUE',
                'doors' => 5,
                'seats' => 5,
                'dimension' => '449 X 179 X 154',
                'additional_features' => ['Power Window', 'Navigation System', 'ProPILOT Assist', 'e-Pedal'],
            ],
            [
                'name' => 'Mazda 3 2022',
                'description' => 'Stylish and sporty compact sedan with premium interior. Great driving dynamics and fuel efficiency.',
                'brand' => 'MAZDA',
                'category' => 'Vehicles',
                'model' => 'Mazda 3',
                'price' => 15200.00,
                'condition' => 'Used',
                'part_number' => 'VH-MAZDA3-2022',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82419',
                'chassis_number' => 'JM1-159****',
                'model_code' => 'BP',
                'year_month' => '2022/5',
                'grade' => 'TOURING',
                'body_style' => 'SEDAN',
                'mileage' => 16000,
                'transmission' => 'AUTOMATIC',
                'engine_cc' => 2000,
                'fuel_type' => 'GASOLINE',
                'color' => 'RED',
                'doors' => 4,
                'seats' => 5,
                'dimension' => '466 X 179 X 144',
                'additional_features' => ['Power Window', 'Bose Sound System', 'Heated Seats', 'Sun Roof'],
            ],
            [
                'name' => 'Suzuki Jimny 2023',
                'description' => 'Compact 4x4 off-road vehicle. Perfect for adventure and outdoor activities. Excellent off-road capability.',
                'brand' => 'SUZUKI',
                'category' => 'Vehicles',
                'model' => 'Jimny',
                'price' => 13200.00,
                'condition' => 'Used',
                'part_number' => 'VH-JIMNY-2023',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82420',
                'chassis_number' => 'JS3-357****',
                'model_code' => 'JB64W',
                'year_month' => '2023/6',
                'grade' => 'XG',
                'body_style' => 'SUV',
                'mileage' => 4000,
                'transmission' => 'MANUAL',
                'engine_cc' => 1500,
                'fuel_type' => 'GASOLINE',
                'color' => 'GREEN',
                'doors' => 3,
                'seats' => 4,
                'dimension' => '364 X 164 X 172',
                'additional_features' => ['Power Window', '4 Wheel Drive', 'Off-road Package', 'Roof Rails'],
            ],
            [
                'name' => 'Toyota Vitz 2023',
                'description' => 'Compact and economical hatchback. Perfect for first-time car owners and city driving.',
                'brand' => 'TOYOTA',
                'category' => 'Vehicles',
                'model' => 'Vitz',
                'price' => 9200.00,
                'condition' => 'Used',
                'part_number' => 'VH-VITZ-2023',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82421',
                'chassis_number' => 'NCP-468****',
                'model_code' => 'XP130',
                'year_month' => '2023/2',
                'grade' => 'U',
                'body_style' => 'HATCHBACK',
                'mileage' => 2500,
                'transmission' => 'CVT',
                'engine_cc' => 1000,
                'fuel_type' => 'GASOLINE',
                'color' => 'WHITE',
                'doors' => 5,
                'seats' => 5,
                'dimension' => '395 X 169 X 151',
                'additional_features' => ['Power Window', 'Keyless Entry', 'Reverse Camera', 'Touchscreen'],
            ],
            [
                'name' => 'Honda Stepwgn 2021',
                'description' => 'Spacious minivan perfect for large families. Versatile seating and excellent cargo space.',
                'brand' => 'HONDA',
                'category' => 'Vehicles',
                'model' => 'Stepwgn',
                'price' => 19800.00,
                'condition' => 'Used',
                'part_number' => 'VH-STEPWGN-2021',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82422',
                'chassis_number' => 'RL5-741****',
                'model_code' => 'RL5',
                'year_month' => '2021/8',
                'grade' => 'G',
                'body_style' => 'MINIVAN',
                'mileage' => 30000,
                'transmission' => 'CVT',
                'engine_cc' => 1500,
                'fuel_type' => 'HYBRID',
                'color' => 'BLACK',
                'doors' => 5,
                'seats' => 8,
                'dimension' => '477 X 174 X 184',
                'additional_features' => ['Power Window', 'Magic Seats', 'Honda Sensing', 'Dual Sliding Doors'],
            ],
            [
                'name' => 'Subaru Impreza 2022',
                'description' => 'All-wheel drive sedan with sporty handling. Great for all weather conditions and driving enthusiasts.',
                'brand' => 'SUBARU',
                'category' => 'Vehicles',
                'model' => 'Impreza',
                'price' => 16200.00,
                'condition' => 'Used',
                'part_number' => 'VH-IMPREZA-2022',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82423',
                'chassis_number' => 'JF1-852****',
                'model_code' => 'GP7',
                'year_month' => '2022/3',
                'grade' => '2.0i',
                'body_style' => 'SEDAN',
                'mileage' => 14000,
                'transmission' => 'CVT',
                'engine_cc' => 2000,
                'fuel_type' => 'GASOLINE',
                'color' => 'BLUE',
                'doors' => 4,
                'seats' => 5,
                'dimension' => '463 X 178 X 145',
                'additional_features' => ['Power Window', '4 Wheel Drive', 'EyeSight System', 'Sun Roof'],
            ],
            [
                'name' => 'Mitsubishi eK Wagon 2023',
                'description' => 'Ultra-compact kei wagon with excellent fuel economy. Perfect for narrow Japanese streets.',
                'brand' => 'MITSUBISHI',
                'category' => 'Vehicles',
                'model' => 'eK Wagon',
                'price' => 7800.00,
                'condition' => 'Used',
                'part_number' => 'VH-EKWAGON-2023',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82424',
                'chassis_number' => 'H52A-963****',
                'model_code' => 'H52A',
                'year_month' => '2023/4',
                'grade' => 'G',
                'body_style' => 'HATCHBACK',
                'mileage' => 2000,
                'transmission' => 'CVT',
                'engine_cc' => 660,
                'fuel_type' => 'GASOLINE',
                'color' => 'ORANGE',
                'doors' => 4,
                'seats' => 4,
                'dimension' => '339 X 147 X 165',
                'additional_features' => ['Power Window', 'Keyless Entry', 'Reverse Camera'],
            ],
            [
                'name' => 'Lexus NX 2021',
                'description' => 'Luxury compact SUV with premium features and excellent build quality. Perfect for those who want comfort and style.',
                'brand' => 'LEXUS',
                'category' => 'Vehicles',
                'model' => 'NX',
                'price' => 28500.00,
                'condition' => 'Used',
                'part_number' => 'VH-NX-2021',
                'stock_quantity' => 1,
                'is_available' => true,
                'stock_id' => '82425',
                'chassis_number' => 'JTJA-147****',
                'model_code' => 'AZ10',
                'year_month' => '2021/9',
                'grade' => 'F SPORT',
                'body_style' => 'SUV',
                'mileage' => 22000,
                'transmission' => 'AUTOMATIC',
                'engine_cc' => 2000,
                'fuel_type' => 'HYBRID',
                'color' => 'SILVER',
                'doors' => 5,
                'seats' => 5,
                'dimension' => '464 X 184 X 164',
                'additional_features' => ['Power Window', 'Mark Levinson Sound', 'Panoramic Sunroof', 'Leather Seats', 'Lexus Safety System'],
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
